import type { EditionFormat } from '../types/Edition'

export const GENRES = [
  'ACAO','AFROFUTURISMO','AJUDA','ALEGORIA','ALTA_FANTASIA','ALTERNATE_HISTORY',
  'ANTOLOGIA','APOLOGETICA','ARTE','ARTIGO','AUTOBIOGRAFIA','AUTOFICCAO','AUTOAJUDA',
  'AVENTURA','AVENTURA_MARITIMA','BILDUNGSROMAN','BIOGRAFIA','CAMPUS_NOVEL','CARTAS',
  'CHICK_LIT','CIENCIA','CIENCIA_POPULAR','CLI_FI','COMEDIA','COMEDIA_DE_COSTUMES',
  'CONSPIRACAO','CONTO','CONTO_DE_FADAS','CONTO_FILOSOFICO','CONTO_LITERARIO',
  'CONTRACULTURA','COZY_FANTASY','COZY_MYSTERY','CRIME','CRONICA','CYBERPUNK',
  'DARK_ACADEMIA','DECADENTISMO','DISTOPIA','DOCUMENTAL','DRAMA','ECOFICTION',
  'ENSAIO','EPISTOLAR','EPOPEIA','ESPADA_E_FEITICARIA','ESPIONAGEM','ESPIRITUALIDADE',
  'FANTASIA','FANTASIA_ARTURIANA','FANTASIA_CIENTIFICA','FANTASIA_EPICA',
  'FANTASIA_HEROICA','FANTASIA_HISTORICA','FANTASIA_MITICA','FANTASIA_SOMBRIA',
  'FAROESTE','FABULA','FEMINISMO','FICCAO_BELICA','FICCAO_CIENTIFICA',
  'FICCAO_CLIMATICA','FICCAO_CONTEMPORANEA','FICCAO_CRISTA','FICCAO_DISTOPICA',
  'FICCAO_ESPIRITUAL','FICCAO_ESPECULATIVA','FICCAO_FILOSOFICA','FICCAO_GOTICA',
  'FICCAO_HISTORICA','FICCAO_HUMANISTA','FICCAO_LITERARIA','FICCAO_MILITAR',
  'FICCAO_POLICIAL','FICCAO_POLITICA','FICCAO_PSICOLOGICA','FICCAO_RELIGIOSA',
  'FICCAO_SATIRICA','FILOSOFIA','FOLCLORE','GASLAMP_FANTASY','GEROFICCAO','GIALLO',
  'GOTICO','GRIMDARK','GUIA','HARD_BOILED','HARD_SCI_FI','HEROIC_FANTASY','HISTORIA',
  'HISTORIA_DA_ARTE','HISTORIA_ORAL','HORROR','HORROR_COSMICO','HORROR_CORPORAL',
  'HORROR_FOLCLORICO','HORROR_PSICOLOGICO','HORROR_RELIGIOSO','HUMOR',
  'INFANTOJUVENIL','JORNALISMO','JORNALISMO_LITERARIO','LEGENDAS_E_MITOS','LITRPG',
  'LITERATURA_EROTICA','LITERATURA_INFANTIL','LITERATURA_JUVENIL','LITERATURA_QUEER',
  'LITERATURA_RUSSA','LITERATURA_LATINO_AMERICANA','MAGICAL_REALISM','MANIFESTO',
  'MANUAL','MEMORIAS','MEDICINA','METAFICCAO','MILITAR','MISTERIO','MITOLOGIA',
  'MOCKUMENTARY','MONOGRAFIA','NARRATIVA_DE_VIAGEM','NARRATIVA_EXPERIMENTAL',
  'NARRATIVA_PICARESCA','NEO_NOIR','NEW_ADULT','NOIR','NOVA_WEIRD','NOVELA',
  'NOVELA_GRAFICA','OCCULT_FICTION','PANFLETO','PARABOLA','PARANORMAL','PERIODISMO',
  'POESIA','POESIA_EPICA','POESIA_LIRICA','POLICIAL','POLITICO','POS_APOCALIPTICO',
  'POS_COLONIAL','PROSA_POETICA','PROGRAMACAO','PSICOLOGIA','REALISMO',
  'REALISMO_MAGICO','REALISMO_PSICOLOGICO','RECORDACOES','RELATO_DE_VIAGEM',
  'RELIGIAO','REPORTAGEM','RETELLING','ROMANCE','ROMANCE_CONTEMPORANEO',
  'ROMANCE_DE_FORMACAO','ROMANCE_DE_COSTUMES','ROMANCE_EPISTOLAR','ROMANCE_GOTICO',
  'ROMANCE_GRAFICO','ROMANCE_HISTORICO','ROMANCE_POLICIAL','ROMANCE_PSICOLOGICO',
  'ROMANCE_RURAL','ROMANCE_UNIVERSITARIO','ROMANTASY','SAGA_FAMILIAR','SATIRA',
  'SCIENCE_FANTASY','SLIPSTREAM','SOCIOLOGIA','SOLARPUNK','SOFT_SCI_FI',
  'SOUTHERN_GOTHIC','SPACE_OPERA','SPLATTERPUNK','STEAMPUNK','STONEPUNK','SUSPENSE',
  'SUSPENSE_JURIDICO','SUSPENSE_PSICOLOGICO','SWORD_AND_PLANET','SWORD_AND_SORCERY',
  'TERROR','TERROR_GOTICO','TERROR_SOBRENATURAL','TESE','THRILLER','THRILLER_ECONOMICO',
  'THRILLER_JURIDICO','THRILLER_MEDICO','THRILLER_MILITAR','THRILLER_POLITICO',
  'THRILLER_PSICOLOGICO','THRILLER_TECNOLOGICO','TRAGEDIA','TRAGICOMEDIA','TRATADO',
  'TRUE_CRIME','UCRONIA','URBAN_FANTASY','VIAGEM','VIAGEM_NO_TEMPO','WEIRD_FICTION',
  'WESTERN','WHODUNIT','YOUNG_ADULT','ZUMBI',
] as const

export const EDITION_FORMATS: EditionFormat[] = [
  'ANIVERSARIO','BILINGUE','BOLSO','BROCHURA','CAPA_DURA','COMEMORATIVA','EPUB','LUXO',
]

export function label(value: string) {
  return value.replace(/_/g, ' ').toLowerCase().replace(/^./, c => c.toUpperCase())
}
